version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"  # Mapea el puerto 5432 del contenedor al puerto 5432 de tu máquina local
    environment:
      POSTGRES_USER: postgres   # Usuario de la base de datos
      POSTGRES_PASSWORD: postgres # Contraseña del usuario
      POSTGRES_DB: la-libreria     # Nombre de la base de datos inicial
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos entre reinicios

volumes:
  postgres_data:
